version: "3.3"

services:
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /home/node/project
    volumes:
        - ./:/home/node/project
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    container_name: dev_node
